<template>
    <div style="margin: 100px;">
        <Select ref="ele" filterable :isSearch="true" v-model="model1" :before-change="beforeChange" :visibleSelcted="visibleSelcted" style="width:200px" prefix="ios-albums">
            <Option v-for="item in slectOps" :value="item.storeId" :key="item.storeId">{{ item.label }}</Option>
        </Select>

        <Select v-model="model10" filterable :max-tag-count="2" multiple style="width:400px">
            <Option v-for="item in cityList" :value="item.value" :key="item.value">{{ item.label }}</Option>
        </Select>

        <Select v-model="model10" filterable :max-tag-count="2" multiple style="width:400px" prefix="ios-albums">
            <Option v-for="item in cityList" :value="item.value" :key="item.value">{{ item.label }}</Option>
        </Select>

        <br><br>

        <Select v-model="model1" style="width:200px">
            <Icon type="ios-alarm" slot="prefix" color="red" />
            <Option v-for="item in cityList" :value="item.value" :key="item.value">{{ item.label }}</Option>
        </Select>

        <Select v-model="model1" style="width:200px">
            <Avatar src="https://dev-file.iviewui.com/userinfoPDvn9gKWYihR24SpgC319vXY8qniCqj4/avatar" slot="prefix" size="small" />
            <Option v-for="item in cityList" :value="item.value" :key="item.value">{{ item.label }}</Option>
        </Select>

        <Select v-model="model10" :max-tag-count="3" :max-tag-placeholder="more" multiple style="width:400px" prefix="ios-albums">
            <Option v-for="item in cityList" :value="item.value" :key="item.value">{{ item.label }}</Option>
        </Select>

        <br><br>

        <Select size="small" v-model="model1" style="width:200px" prefix="ios-albums">
            <Option v-for="item in cityList" :value="item.value" :key="item.value">{{ item.label }}</Option>
        </Select>

        <Select size="small" v-model="model10" multiple style="width:400px" prefix="ios-albums">
            <Option v-for="item in cityList" :value="item.value" :key="item.value">{{ item.label }}</Option>
        </Select>

        <br><br>

        <Select size="large" v-model="model1" style="width:200px" prefix="ios-albums">
            <Option v-for="item in cityList" :value="item.value" :key="item.value">{{ item.label }}</Option>
        </Select>

        <Select size="large" v-model="model10" multiple style="width:400px" prefix="ios-albums">
            <Option v-for="item in cityList" :value="item.value" :key="item.value">{{ item.label }}</Option>
        </Select>
        <Divider></Divider>
        <Select v-model="model13" filterable allow-create @on-create="handleCreate" style="width:260px">
            <Option v-for="item in cityList" :value="item.value" :key="item.value">{{ item.label }}</Option>
        </Select>
        <Select v-model="model12" multiple filterable allow-create @on-create="handleCreate" style="width:260px">
            <Option v-for="item in cityList" :value="item.value" :key="item.value">{{ item.label }}</Option>
        </Select>
        <Divider></Divider>
        <Select v-model="model31" size="small" style="width:200px">
            <Option v-for="item in cityList" :value="item.value" :key="item.value">{{ item.label }}</Option>
        </Select>
        <Select v-model="model31" style="width:200px">
            <Option v-for="item in cityList" :value="item.value" :key="item.value">{{ item.label }}</Option>
        </Select>
        <Select v-model="model31" size="large" style="width:200px">
            <Option v-for="item in cityList" :value="item.value" :key="item.value">{{ item.label }}</Option>
        </Select>
        <Divider></Divider>
        <Select v-model="model31" filterable size="small" style="width:200px">
            <Option v-for="item in cityList" :value="item.value" :key="item.value">{{ item.label }}</Option>
        </Select>
        <Select v-model="model31" filterable style="width:200px">
            <Option v-for="item in cityList" :value="item.value" :key="item.value">{{ item.label }}</Option>
        </Select>
        <Select v-model="model31" filterable size="large" style="width:200px">
            <Option v-for="item in cityList" :value="item.value" :key="item.value">{{ item.label }}</Option>
        </Select>
        <Divider></Divider>
        <Select v-model="model34" multiple size="small" style="width:200px">
            <Option v-for="item in cityList" :value="item.value" :key="item.value">{{ item.label }}</Option>
        </Select>
        <Select v-model="model34" multiple style="width:200px">
            <Option v-for="item in cityList" :value="item.value" :key="item.value">{{ item.label }}</Option>
        </Select>
        <Select v-model="model34" multiple size="large" style="width:200px">
            <Option v-for="item in cityList" :value="item.value" :key="item.value">{{ item.label }}</Option>
        </Select>
        <Divider></Divider>
        <Select v-model="model34" filterable multiple size="small" style="width:200px">
            <Option v-for="item in cityList" :value="item.value" :key="item.value">{{ item.label }}</Option>
        </Select>
        <Select v-model="model34" filterable multiple style="width:200px">
            <Option v-for="item in cityList" :value="item.value" :key="item.value">{{ item.label }}</Option>
        </Select>
        <Select v-model="model34" filterable allow-create multiple size="large" style="width:200px">
            <Option v-for="item in cityList" :value="item.value" :key="item.value">{{ item.label }}</Option>
        </Select>
    </div>
</template>
<script>
    export default {
        data () {
            return {
                visibleSelcted:false,
                slectOps:[
                    {
                        "storeId": 1,
                        "storeNo": "S000001",
                        "businessLicenceImageUrl": "",
                        "bankLicence": "http://pipainfo.oss-cn-beijing.aliyuncs.com/PC/-1/2019-04/03/20190493152754089512.png",
                        "storeTypeId": 95,
                        "storeTypeName": "美妆美容",
                        "companyName": "北京食无忧电子商务有限公司",
                        "companyAreaNo": "110108",
                        "companyAddress": "海淀区北太平庄路18号城建大厦A座8楼",
                        "companyPhone": "88888888",
                        "foodCirculationPermitImageUrl": "http://swy-mall-project.oss-cn-zhangjiakou.aliyuncs.com/PC/6/2021-12/03/202112337103545407556.png,http://swy-mall-project.oss-cn-zhangjiakou.aliyuncs.com/PC/-1/2021-12/10/202112344133520952619.jpg",
                        "storeLevelId": 1,
                        "storeLevelName": "一星级",
                        "hasBusinessLicence": null,
                        "hasFoodCirculationPermit": null,
                        "flagOwnShop": "1",
                        "flagRecommend": "1",
                        "sellerId": 1,
                        "sellerName": "19000000001",
                        "state": 1,
                        "freezeTime": null,
                        "freezeEndTime": null,
                        "freezeDuration": null,
                        "freezeDurationUnit": null,
                        "freezeReason": null,
                        "areaNo": "110108",
                        "storeAddress": "丰台区外环西路26号院17号楼",
                        "storeAvatarUrl": "http://swy-mall-project.oss-cn-zhangjiakou.aliyuncs.com/PC/-1/2020-10/12/202010286140524744892.png",
                        "storeCoverUrl": "http://swy-mall-project.oss-cn-zhangjiakou.aliyuncs.com/PC/-1/2021-12/10/202112344112322478690.png",
                        "storeCollect": null,
                        "storeEndTime": "2025-01-31 00:00:00",
                        "storeLogoUrl": "http://swy-mall-project.oss-cn-zhangjiakou.aliyuncs.com/PC/-1/2020-10/12/202010286140518865426.png",
                        "storeName": "食无忧商城",
                        "storePhone": "18612394866",
                        "storeSales": null,
                        "storeZy": null,
                        "minPrice": null,
                        "longitude": "114.250861",
                        "latitude": "30.592748",
                        "sellerService": "北京食无忧电子商务有限公司于2017年6月在北京注册成立，自成立以来，秉承“民以食为天，食以安为先”的经营理念，以专业推介安全放心食品为己任，积极贯彻执行国家食品安全发展战略，庄严承诺让社会全体公民“买得放心，吃得安心”是公司肩负的社会责任与使命，也是永恒的信念。\n      北京食无忧电子商务有限公司采用“互联网+技术创新+营销创新+服务创新”四位一体的创新型商业模式，积极践行国家食品安全战略，力求全力打造从“源头到餐桌”的食品安全体系，让广大消费者吃到健康、放心的食品，从而营造“健康、美味、营养、保真”的绿色食品概念。\n    《食无忧保真商城》上架的产品均为全国产品防伪溯源验证公共平台提供全程溯源监管，中国侵权假冒物品检验鉴定公共平台提供全面品质把控，多家知名保险公司提供产品质量保证保险，北京食无忧电子商务有限公司精选的包括国家地标产品、非遗产品、地方政府主推的名优特产品、品牌食品、龙头企业产品、国家贫困县特色产品、精准扶贫优质产品等一系列放心型产品。",
                        "scopeBusiness": "食无忧公司经营范围为：销售电子产品；货物进出口；技术进出口；代理进出口；销售食品。",
                        "unifiedSocialCreditCode": "91110105MA017GNY4K",
                        "freightTempMode": 3,
                        "freightRules": 1,
                        "isSupportReturnedCoupon": 1,
                        "groupBookingRules": "规则规则1111",
                        "isAutoFillCost": 1,
                        "costRatioValue": 20,
                        "createTime": "2019-03-28 00:00:00",
                        "uptTime": "2021-12-13 16:44:13",
                        "updateBy": 14,
                        "remarks": "encorehe",
                        "flagDel": "0",
                        "label": "食无忧商城"
                    },
                    {
                        "storeId": 2,
                        "storeNo": "S000002",
                        "businessLicenceImageUrl": null,
                        "bankLicence": null,
                        "storeTypeId": 98,
                        "storeTypeName": "美妆饰品",
                        "companyName": "武汉可爱多一点有限公司",
                        "companyAreaNo": "420102",
                        "companyAddress": "泛海国际1栋308",
                        "companyPhone": "877662817",
                        "foodCirculationPermitImageUrl": "http://swy-mall-project.oss-cn-zhangjiakou.aliyuncs.com/PC/-1/2021-12/10/202112344133611654022.jpg",
                        "storeLevelId": 1,
                        "storeLevelName": "一星级",
                        "hasBusinessLicence": null,
                        "hasFoodCirculationPermit": null,
                        "flagOwnShop": "0",
                        "flagRecommend": "1",
                        "sellerId": 77,
                        "sellerName": "13987787665",
                        "state": 1,
                        "freezeTime": null,
                        "freezeEndTime": null,
                        "freezeDuration": null,
                        "freezeDurationUnit": null,
                        "freezeReason": null,
                        "areaNo": "420102",
                        "storeAddress": "泛海国际1栋308",
                        "storeAvatarUrl": "http://swy-mall-project.oss-cn-zhangjiakou.aliyuncs.com/PC/-1/2021-12/10/202112344133624730697.jpg",
                        "storeCoverUrl": null,
                        "storeCollect": null,
                        "storeEndTime": "2021-12-21 00:00:00",
                        "storeLogoUrl": "http://swy-mall-project.oss-cn-zhangjiakou.aliyuncs.com/PC/-1/2021-12/10/202112344133621057473.jpg",
                        "storeName": "木兰天池养老基地",
                        "storePhone": "13987787665",
                        "storeSales": null,
                        "storeZy": null,
                        "minPrice": null,
                        "longitude": "114.284152",
                        "latitude": "30.584826",
                        "sellerService": null,
                        "scopeBusiness": "国内旅游业务，境内旅游业务；旅游纪念品销售",
                        "unifiedSocialCreditCode": "913099897372722",
                        "freightTempMode": 3,
                        "freightRules": 1,
                        "isSupportReturnedCoupon": 0,
                        "groupBookingRules": "",
                        "isAutoFillCost": 0,
                        "costRatioValue": 0,
                        "createTime": "2021-05-19 00:00:00",
                        "uptTime": "2021-12-10 13:37:05",
                        "updateBy": 14,
                        "remarks": "encorehe",
                        "flagDel": "0",
                        "label": "木兰天池养老基地"
                    },
                    {
                        "storeId": 3,
                        "storeNo": "S000003",
                        "businessLicenceImageUrl": "",
                        "bankLicence": "",
                        "storeTypeId": 95,
                        "storeTypeName": "百货食品",
                        "companyName": null,
                        "companyAreaNo": null,
                        "companyAddress": null,
                        "companyPhone": null,
                        "foodCirculationPermitImageUrl": "http://swy-mall-project.oss-cn-zhangjiakou.aliyuncs.com/PC/-1/2021-12/14/202112348112942976877.jpg",
                        "storeLevelId": null,
                        "storeLevelName": null,
                        "hasBusinessLicence": null,
                        "hasFoodCirculationPermit": null,
                        "flagOwnShop": "0",
                        "flagRecommend": null,
                        "sellerId": null,
                        "sellerName": "S19000000002",
                        "state": 1,
                        "freezeTime": null,
                        "freezeEndTime": null,
                        "freezeDuration": null,
                        "freezeDurationUnit": null,
                        "freezeReason": null,
                        "areaNo": "110108",
                        "storeAddress": "武汉市江汉区",
                        "storeAvatarUrl": "xxx",
                        "storeCoverUrl": "http://swy-mall-project.oss-cn-zhangjiakou.aliyuncs.com/PC/-1/2021-12/10/202112344112340816906.jpg",
                        "storeCollect": null,
                        "storeEndTime": "2030-12-31 00:00:00",
                        "storeLogoUrl": "xx",
                        "storeName": "测试店铺111",
                        "storePhone": "17764019614",
                        "storeSales": null,
                        "storeZy": null,
                        "minPrice": null,
                        "longitude": "30.592748",
                        "latitude": "114.250861",
                        "sellerService": "店铺简介test店铺简介test店铺简介test店铺简介test店铺简介test店铺简介test店铺简介test",
                        "scopeBusiness": null,
                        "unifiedSocialCreditCode": null,
                        "freightTempMode": 3,
                        "freightRules": 1,
                        "isSupportReturnedCoupon": 0,
                        "groupBookingRules": null,
                        "isAutoFillCost": 0,
                        "costRatioValue": 0,
                        "createTime": "2025-07-31 00:00:00",
                        "uptTime": "2021-12-14 11:30:13",
                        "updateBy": 14,
                        "remarks": "encorehe",
                        "flagDel": "0",
                        "label": "测试店铺111"
                    },
                    {
                        "storeId": 4,
                        "storeNo": "S000004",
                        "businessLicenceImageUrl": "http://swy-mall-project.oss-cn-zhangjiakou.aliyuncs.com/PC/-1/2021-12/02/202112336154520843986.png",
                        "bankLicence": "http://swy-mall-project.oss-cn-zhangjiakou.aliyuncs.com/PC/-1/2021-12/02/202112336154523754409.png",
                        "storeTypeId": 98,
                        "storeTypeName": "美妆饰品",
                        "companyName": null,
                        "companyAreaNo": null,
                        "companyAddress": null,
                        "companyPhone": null,
                        "foodCirculationPermitImageUrl": null,
                        "storeLevelId": null,
                        "storeLevelName": null,
                        "hasBusinessLicence": null,
                        "hasFoodCirculationPermit": null,
                        "flagOwnShop": "0",
                        "flagRecommend": null,
                        "sellerId": null,
                        "sellerName": "test",
                        "state": 2,
                        "freezeTime": null,
                        "freezeEndTime": null,
                        "freezeDuration": null,
                        "freezeDurationUnit": null,
                        "freezeReason": "",
                        "areaNo": "110101",
                        "storeAddress": "test",
                        "storeAvatarUrl": "http://swy-mall-project.oss-cn-zhangjiakou.aliyuncs.com/PC/-1/2021-12/02/202112336154509858544.png",
                        "storeCoverUrl": null,
                        "storeCollect": null,
                        "storeEndTime": "2021-12-03 00:00:00",
                        "storeLogoUrl": "http://swy-mall-project.oss-cn-zhangjiakou.aliyuncs.com/PC/-1/2021-12/02/202112336154505475317.png",
                        "storeName": "test",
                        "storePhone": "111",
                        "storeSales": null,
                        "storeZy": null,
                        "minPrice": null,
                        "longitude": "114.288873",
                        "latitude": "30.585759",
                        "sellerService": "111",
                        "scopeBusiness": null,
                        "unifiedSocialCreditCode": null,
                        "freightTempMode": 3,
                        "freightRules": 1,
                        "isSupportReturnedCoupon": 0,
                        "groupBookingRules": null,
                        "isAutoFillCost": 0,
                        "costRatioValue": 0,
                        "createTime": "2021-12-21 00:00:00",
                        "uptTime": "2021-12-02 15:45:35",
                        "updateBy": 14,
                        "remarks": "encorehe",
                        "flagDel": "0",
                        "label": "test"
                    },
                    {
                        "storeId": 5,
                        "storeNo": "S000005",
                        "businessLicenceImageUrl": "http://swy-mall-project.oss-cn-zhangjiakou.aliyuncs.com/PC/-1/2021-12/02/202112336155437488624.png",
                        "bankLicence": "http://swy-mall-project.oss-cn-zhangjiakou.aliyuncs.com/PC/-1/2021-12/02/202112336155441517670.png",
                        "storeTypeId": 94,
                        "storeTypeName": "服装鞋包",
                        "companyName": null,
                        "companyAreaNo": null,
                        "companyAddress": null,
                        "companyPhone": null,
                        "foodCirculationPermitImageUrl": null,
                        "storeLevelId": null,
                        "storeLevelName": null,
                        "hasBusinessLicence": null,
                        "hasFoodCirculationPermit": null,
                        "flagOwnShop": "0",
                        "flagRecommend": null,
                        "sellerId": null,
                        "sellerName": "test2",
                        "state": 2,
                        "freezeTime": null,
                        "freezeEndTime": null,
                        "freezeDuration": null,
                        "freezeDurationUnit": null,
                        "freezeReason": "",
                        "areaNo": "150524",
                        "storeAddress": "111",
                        "storeAvatarUrl": "http://swy-mall-project.oss-cn-zhangjiakou.aliyuncs.com/PC/-1/2021-12/02/202112336155427843974.png",
                        "storeCoverUrl": null,
                        "storeCollect": null,
                        "storeEndTime": "2021-12-09 00:00:00",
                        "storeLogoUrl": "http://swy-mall-project.oss-cn-zhangjiakou.aliyuncs.com/PC/-1/2021-12/02/202112336155423288992.png",
                        "storeName": "test2",
                        "storePhone": "111",
                        "storeSales": null,
                        "storeZy": null,
                        "minPrice": null,
                        "longitude": "114.282672",
                        "latitude": "30.585759",
                        "sellerService": "111",
                        "scopeBusiness": null,
                        "unifiedSocialCreditCode": null,
                        "freightTempMode": 3,
                        "freightRules": 1,
                        "isSupportReturnedCoupon": 0,
                        "groupBookingRules": null,
                        "isAutoFillCost": 0,
                        "costRatioValue": 0,
                        "createTime": "2021-12-02 00:00:00",
                        "uptTime": "2021-12-02 15:55:07",
                        "updateBy": 14,
                        "remarks": "encorehe",
                        "flagDel": "0",
                        "label": "test2"
                    },
                    {
                        "storeId": 6,
                        "storeNo": "S000006",
                        "businessLicenceImageUrl": "",
                        "bankLicence": "http://pipainfo.oss-cn-beijing.aliyuncs.com/PC/-1/2019-04/03/20190493152754089512.png",
                        "storeTypeId": 95,
                        "storeTypeName": "美妆美容",
                        "companyName": null,
                        "companyAreaNo": null,
                        "companyAddress": null,
                        "companyPhone": null,
                        "foodCirculationPermitImageUrl": null,
                        "storeLevelId": null,
                        "storeLevelName": null,
                        "hasBusinessLicence": null,
                        "hasFoodCirculationPermit": null,
                        "flagOwnShop": "1",
                        "flagRecommend": null,
                        "sellerId": null,
                        "sellerName": null,
                        "state": 2,
                        "freezeTime": null,
                        "freezeEndTime": null,
                        "freezeDuration": null,
                        "freezeDurationUnit": null,
                        "freezeReason": null,
                        "areaNo": "110108",
                        "storeAddress": "丰台区外环西路26号院17号楼",
                        "storeAvatarUrl": "http://swy-mall-project.oss-cn-zhangjiakou.aliyuncs.com/PC/-1/2020-10/12/202010286140524744892.png",
                        "storeCoverUrl": null,
                        "storeCollect": null,
                        "storeEndTime": "2025-01-31 00:00:00",
                        "storeLogoUrl": "http://swy-mall-project.oss-cn-zhangjiakou.aliyuncs.com/PC/-1/2020-10/12/202010286140518865426.png",
                        "storeName": "食无忧商城2",
                        "storePhone": "18612394866",
                        "storeSales": null,
                        "storeZy": null,
                        "minPrice": null,
                        "longitude": "114.250861",
                        "latitude": "30.592748",
                        "sellerService": "北京食无忧电子商务有限公司于2017年6月在北京注册成立，自成立以来，秉承“民以食为天，食以安为先”的经营理念，以专业推介安全放心食品为己任，积极贯彻执行国家食品安全发展战略，庄严承诺让社会全体公民“买得放心，吃得安心”是公司肩负的社会责任与使命，也是永恒的信念。\n      北京食无忧电子商务有限公司采用“互联网+技术创新+营销创新+服务创新”四位一体的创新型商业模式，积极践行国家食品安全战略，力求全力打造从“源头到餐桌”的食品安全体系，让广大消费者吃到健康、放心的食品，从而营造“健康、美味、营养、保真”的绿色食品概念。\n    《食无忧保真商城》上架的产品均为全国产品防伪溯源验证公共平台提供全程溯源监管，中国侵权假冒物品检验鉴定公共平台提供全面品质把控，多家知名保险公司提供产品质量保证保险，北京食无忧电子商务有限公司精选的包括国家地标产品、非遗产品、地方政府主推的名优特产品、品牌食品、龙头企业产品、国家贫困县特色产品、精准扶贫优质产品等一系列放心型产品。",
                        "scopeBusiness": null,
                        "unifiedSocialCreditCode": null,
                        "freightTempMode": 3,
                        "freightRules": 1,
                        "isSupportReturnedCoupon": 0,
                        "groupBookingRules": null,
                        "isAutoFillCost": 0,
                        "costRatioValue": 0,
                        "createTime": "2019-03-28 00:00:00",
                        "uptTime": "2021-12-02 18:53:37",
                        "updateBy": 14,
                        "remarks": "encorehe",
                        "flagDel": "0",
                        "label": "食无忧商城2"
                    },
                    {
                        "storeId": 7,
                        "storeNo": "S000007",
                        "businessLicenceImageUrl": "http://swy-mall-project.oss-cn-zhangjiakou.aliyuncs.com/PC/-1/2021-12/03/202112337102845391930.png",
                        "bankLicence": "http://swy-mall-project.oss-cn-zhangjiakou.aliyuncs.com/PC/-1/2021-12/03/202112337102849584354.png",
                        "storeTypeId": 94,
                        "storeTypeName": "服装鞋包",
                        "companyName": null,
                        "companyAreaNo": null,
                        "companyAddress": null,
                        "companyPhone": null,
                        "foodCirculationPermitImageUrl": "http://swy-mall-project.oss-cn-zhangjiakou.aliyuncs.com/PC/6/2021-12/03/202112337102856675119.png",
                        "storeLevelId": null,
                        "storeLevelName": null,
                        "hasBusinessLicence": null,
                        "hasFoodCirculationPermit": null,
                        "flagOwnShop": "0",
                        "flagRecommend": null,
                        "sellerId": null,
                        "sellerName": "test",
                        "state": 2,
                        "freezeTime": null,
                        "freezeEndTime": null,
                        "freezeDuration": null,
                        "freezeDurationUnit": null,
                        "freezeReason": "",
                        "areaNo": "210521",
                        "storeAddress": "1111",
                        "storeAvatarUrl": "http://swy-mall-project.oss-cn-zhangjiakou.aliyuncs.com/PC/-1/2021-12/03/202112337102831054148.png",
                        "storeCoverUrl": "http://swy-mall-project.oss-cn-zhangjiakou.aliyuncs.com/PC/-1/2021-12/03/202112337102853327993.jpg",
                        "storeCollect": null,
                        "storeEndTime": "2021-12-16 00:00:00",
                        "storeLogoUrl": "http://swy-mall-project.oss-cn-zhangjiakou.aliyuncs.com/PC/-1/2021-12/03/202112337102827132483.png",
                        "storeName": "test2",
                        "storePhone": "test",
                        "storeSales": null,
                        "storeZy": null,
                        "minPrice": null,
                        "longitude": "114.282886",
                        "latitude": "30.5855",
                        "sellerService": "tes",
                        "scopeBusiness": null,
                        "unifiedSocialCreditCode": null,
                        "freightTempMode": 3,
                        "freightRules": 1,
                        "isSupportReturnedCoupon": 0,
                        "groupBookingRules": null,
                        "isAutoFillCost": 0,
                        "costRatioValue": 0,
                        "createTime": "2021-12-03 00:00:00",
                        "uptTime": "2021-12-03 10:29:54",
                        "updateBy": 14,
                        "remarks": "encorehe",
                        "flagDel": "0",
                        "label": "test2"
                    },
                    {
                        "storeId": 13,
                        "storeNo": "S000008",
                        "businessLicenceImageUrl": "xxxx",
                        "bankLicence": "xxx",
                        "storeTypeId": null,
                        "storeTypeName": "美妆美容",
                        "companyName": null,
                        "companyAreaNo": null,
                        "companyAddress": null,
                        "companyPhone": null,
                        "foodCirculationPermitImageUrl": null,
                        "storeLevelId": null,
                        "storeLevelName": null,
                        "hasBusinessLicence": null,
                        "hasFoodCirculationPermit": null,
                        "flagOwnShop": "0",
                        "flagRecommend": null,
                        "sellerId": null,
                        "sellerName": "19000000002",
                        "state": 2,
                        "freezeTime": null,
                        "freezeEndTime": null,
                        "freezeDuration": null,
                        "freezeDurationUnit": null,
                        "freezeReason": null,
                        "areaNo": "110108",
                        "storeAddress": "武汉市江汉区",
                        "storeAvatarUrl": "xxx",
                        "storeCoverUrl": null,
                        "storeCollect": null,
                        "storeEndTime": "2030-12-31 00:00:00",
                        "storeLogoUrl": "xx",
                        "storeName": "测试店铺2",
                        "storePhone": "17764019614",
                        "storeSales": null,
                        "storeZy": null,
                        "minPrice": null,
                        "longitude": "30.592748",
                        "latitude": "114.250861",
                        "sellerService": "店铺简介test店铺简介test店铺简介test店铺简介test店铺简介test店铺简介test店铺简介test",
                        "scopeBusiness": null,
                        "unifiedSocialCreditCode": null,
                        "freightTempMode": 3,
                        "freightRules": 1,
                        "isSupportReturnedCoupon": 0,
                        "groupBookingRules": null,
                        "isAutoFillCost": 0,
                        "costRatioValue": 0,
                        "createTime": "2025-07-31 00:00:00",
                        "uptTime": "2021-12-03 15:34:42",
                        "updateBy": 29,
                        "remarks": null,
                        "flagDel": "0",
                        "label": "测试店铺2"
                    },
                    {
                        "storeId": 14,
                        "storeNo": "S000009",
                        "businessLicenceImageUrl": "",
                        "bankLicence": "",
                        "storeTypeId": 95,
                        "storeTypeName": "百货食品",
                        "companyName": null,
                        "companyAreaNo": null,
                        "companyAddress": null,
                        "companyPhone": null,
                        "foodCirculationPermitImageUrl": "",
                        "storeLevelId": null,
                        "storeLevelName": null,
                        "hasBusinessLicence": null,
                        "hasFoodCirculationPermit": null,
                        "flagOwnShop": "0",
                        "flagRecommend": null,
                        "sellerId": null,
                        "sellerName": "SIO555666888999",
                        "state": 2,
                        "freezeTime": null,
                        "freezeEndTime": null,
                        "freezeDuration": null,
                        "freezeDurationUnit": null,
                        "freezeReason": "",
                        "areaNo": "110102",
                        "storeAddress": "西单广场105大街366号",
                        "storeAvatarUrl": "http://swy-mall-project.oss-cn-zhangjiakou.aliyuncs.com/PC/-1/2021-12/08/202112342182114779618.png",
                        "storeCoverUrl": "",
                        "storeCollect": null,
                        "storeEndTime": "2030-12-31 00:00:00",
                        "storeLogoUrl": "http://swy-mall-project.oss-cn-zhangjiakou.aliyuncs.com/PC/-1/2021-12/08/202112342182102252646.png",
                        "storeName": "测试1号店",
                        "storePhone": "010-88996655",
                        "storeSales": null,
                        "storeZy": null,
                        "minPrice": null,
                        "longitude": "115.748832",
                        "latitude": "40.432599",
                        "sellerService": "第三方店铺",
                        "scopeBusiness": null,
                        "unifiedSocialCreditCode": null,
                        "freightTempMode": 3,
                        "freightRules": 1,
                        "isSupportReturnedCoupon": 0,
                        "groupBookingRules": null,
                        "isAutoFillCost": 0,
                        "costRatioValue": 0,
                        "createTime": "2021-12-01 00:00:00",
                        "uptTime": "2021-12-08 18:40:24",
                        "updateBy": 19,
                        "remarks": "yuying",
                        "flagDel": "1",
                        "label": "测试1号店"
                    },
                    {
                        "storeId": 15,
                        "storeNo": "S000010",
                        "businessLicenceImageUrl": "",
                        "bankLicence": "",
                        "storeTypeId": 95,
                        "storeTypeName": "百货食品",
                        "companyName": null,
                        "companyAreaNo": null,
                        "companyAddress": null,
                        "companyPhone": null,
                        "foodCirculationPermitImageUrl": "",
                        "storeLevelId": null,
                        "storeLevelName": null,
                        "hasBusinessLicence": null,
                        "hasFoodCirculationPermit": null,
                        "flagOwnShop": "0",
                        "flagRecommend": null,
                        "sellerId": null,
                        "sellerName": "SIO555666888999",
                        "state": 2,
                        "freezeTime": null,
                        "freezeEndTime": null,
                        "freezeDuration": null,
                        "freezeDurationUnit": null,
                        "freezeReason": "",
                        "areaNo": "110102",
                        "storeAddress": "西单广场105大街366号",
                        "storeAvatarUrl": "http://swy-mall-project.oss-cn-zhangjiakou.aliyuncs.com/PC/-1/2021-12/08/202112342182114779618.png",
                        "storeCoverUrl": "",
                        "storeCollect": null,
                        "storeEndTime": "2030-12-31 00:00:00",
                        "storeLogoUrl": "http://swy-mall-project.oss-cn-zhangjiakou.aliyuncs.com/PC/-1/2021-12/08/202112342182102252646.png",
                        "storeName": "测试1号店",
                        "storePhone": "010-88996655",
                        "storeSales": null,
                        "storeZy": null,
                        "minPrice": null,
                        "longitude": "115.748832",
                        "latitude": "40.432599",
                        "sellerService": "第三方店铺",
                        "scopeBusiness": null,
                        "unifiedSocialCreditCode": null,
                        "freightTempMode": 3,
                        "freightRules": 1,
                        "isSupportReturnedCoupon": 0,
                        "groupBookingRules": null,
                        "isAutoFillCost": 0,
                        "costRatioValue": 0,
                        "createTime": "2021-12-01 00:00:00",
                        "uptTime": "2021-12-08 19:33:57",
                        "updateBy": 19,
                        "remarks": "yuying",
                        "flagDel": "0",
                        "label": "测试1号店"
                    },
                    {
                        "storeId": 16,
                        "storeNo": "S000011",
                        "businessLicenceImageUrl": "",
                        "bankLicence": "",
                        "storeTypeId": 94,
                        "storeTypeName": "服装鞋包",
                        "companyName": null,
                        "companyAreaNo": null,
                        "companyAddress": null,
                        "companyPhone": null,
                        "foodCirculationPermitImageUrl": "",
                        "storeLevelId": null,
                        "storeLevelName": null,
                        "hasBusinessLicence": null,
                        "hasFoodCirculationPermit": null,
                        "flagOwnShop": "0",
                        "flagRecommend": null,
                        "sellerId": null,
                        "sellerName": "aaa",
                        "state": 2,
                        "freezeTime": null,
                        "freezeEndTime": null,
                        "freezeDuration": null,
                        "freezeDurationUnit": null,
                        "freezeReason": "",
                        "areaNo": "150524",
                        "storeAddress": "111",
                        "storeAvatarUrl": "http://swy-mall-project.oss-cn-zhangjiakou.aliyuncs.com/PC/-1/2021-12/09/202112343153239391430.jpg",
                        "storeCoverUrl": "",
                        "storeCollect": null,
                        "storeEndTime": "2021-12-10 00:00:00",
                        "storeLogoUrl": "http://swy-mall-project.oss-cn-zhangjiakou.aliyuncs.com/PC/-1/2021-12/09/202112343153235361031.jpg",
                        "storeName": "bbb",
                        "storePhone": "",
                        "storeSales": null,
                        "storeZy": null,
                        "minPrice": null,
                        "longitude": "114.295182",
                        "latitude": "30.584937",
                        "sellerService": "",
                        "scopeBusiness": null,
                        "unifiedSocialCreditCode": null,
                        "freightTempMode": 3,
                        "freightRules": 1,
                        "isSupportReturnedCoupon": 0,
                        "groupBookingRules": null,
                        "isAutoFillCost": 0,
                        "costRatioValue": 0,
                        "createTime": "2021-12-09 00:00:00",
                        "uptTime": "2021-12-09 15:32:51",
                        "updateBy": 14,
                        "remarks": "encorehe",
                        "flagDel": "0",
                        "label": "bbb"
                    },
                    {
                        "storeId": 17,
                        "storeNo": "S000012",
                        "businessLicenceImageUrl": "",
                        "bankLicence": "",
                        "storeTypeId": 98,
                        "storeTypeName": "美妆饰品",
                        "companyName": null,
                        "companyAreaNo": null,
                        "companyAddress": null,
                        "companyPhone": null,
                        "foodCirculationPermitImageUrl": "http://swy-mall-project.oss-cn-zhangjiakou.aliyuncs.com/PC/-1/2021-12/14/202112348103855151193.png,http://swy-mall-project.oss-cn-zhangjiakou.aliyuncs.com/PC/-1/2021-12/14/202112348103859775330.png,http://swy-mall-project.oss-cn-zhangjiakou.aliyuncs.com/PC/-1/2021-12/14/202112348103905753773.png",
                        "storeLevelId": null,
                        "storeLevelName": null,
                        "hasBusinessLicence": null,
                        "hasFoodCirculationPermit": null,
                        "flagOwnShop": "0",
                        "flagRecommend": null,
                        "sellerId": null,
                        "sellerName": "Ts",
                        "state": 1,
                        "freezeTime": null,
                        "freezeEndTime": null,
                        "freezeDuration": null,
                        "freezeDurationUnit": null,
                        "freezeReason": "",
                        "areaNo": "110101",
                        "storeAddress": "dad",
                        "storeAvatarUrl": "http://swy-mall-project.oss-cn-zhangjiakou.aliyuncs.com/PC/-1/2021-12/13/202112347170149152676.jpg",
                        "storeCoverUrl": "",
                        "storeCollect": null,
                        "storeEndTime": "2021-12-14 00:00:00",
                        "storeLogoUrl": "http://swy-mall-project.oss-cn-zhangjiakou.aliyuncs.com/PC/-1/2021-12/13/202112347170145583436.jpg",
                        "storeName": "dd",
                        "storePhone": "13026368745",
                        "storeSales": null,
                        "storeZy": null,
                        "minPrice": null,
                        "longitude": "114.292339",
                        "latitude": "30.585537",
                        "sellerService": "aa",
                        "scopeBusiness": null,
                        "unifiedSocialCreditCode": null,
                        "freightTempMode": 3,
                        "freightRules": 1,
                        "isSupportReturnedCoupon": 0,
                        "groupBookingRules": null,
                        "isAutoFillCost": 0,
                        "costRatioValue": 0,
                        "createTime": "2021-12-13 00:00:00",
                        "uptTime": "2021-12-13 17:02:05",
                        "updateBy": 14,
                        "remarks": "encorehe",
                        "flagDel": "0",
                        "label": "dd"
                    },
                    {
                        "storeId": 18,
                        "storeNo": "S000013",
                        "businessLicenceImageUrl": "",
                        "bankLicence": "",
                        "storeTypeId": 94,
                        "storeTypeName": "服装鞋包",
                        "companyName": null,
                        "companyAreaNo": null,
                        "companyAddress": null,
                        "companyPhone": null,
                        "foodCirculationPermitImageUrl": "",
                        "storeLevelId": null,
                        "storeLevelName": null,
                        "hasBusinessLicence": null,
                        "hasFoodCirculationPermit": null,
                        "flagOwnShop": "0",
                        "flagRecommend": null,
                        "sellerId": null,
                        "sellerName": "13026368745",
                        "state": 1,
                        "freezeTime": null,
                        "freezeEndTime": null,
                        "freezeDuration": null,
                        "freezeDurationUnit": null,
                        "freezeReason": "",
                        "areaNo": "110101",
                        "storeAddress": "eee",
                        "storeAvatarUrl": "http://swy-mall-project.oss-cn-zhangjiakou.aliyuncs.com/PC/-1/2021-12/14/202112348165751330500.png",
                        "storeCoverUrl": "",
                        "storeCollect": null,
                        "storeEndTime": "2021-12-15 00:00:00",
                        "storeLogoUrl": "http://swy-mall-project.oss-cn-zhangjiakou.aliyuncs.com/PC/-1/2021-12/14/202112348165748434266.png",
                        "storeName": "aaa",
                        "storePhone": "",
                        "storeSales": null,
                        "storeZy": null,
                        "minPrice": null,
                        "longitude": "114.297821",
                        "latitude": "30.586562",
                        "sellerService": "",
                        "scopeBusiness": null,
                        "unifiedSocialCreditCode": null,
                        "freightTempMode": 3,
                        "freightRules": 1,
                        "isSupportReturnedCoupon": 0,
                        "groupBookingRules": null,
                        "isAutoFillCost": 0,
                        "costRatioValue": 0,
                        "createTime": "2021-12-14 00:00:00",
                        "uptTime": "2021-12-14 16:58:01",
                        "updateBy": 14,
                        "remarks": "encorehe",
                        "flagDel": "0",
                        "label": "aaa"
                    },
                    {
                        "storeId": 19,
                        "storeNo": "S000014",
                        "businessLicenceImageUrl": "",
                        "bankLicence": "",
                        "storeTypeId": 99,
                        "storeTypeName": "母婴用品",
                        "companyName": null,
                        "companyAreaNo": null,
                        "companyAddress": null,
                        "companyPhone": null,
                        "foodCirculationPermitImageUrl": "",
                        "storeLevelId": null,
                        "storeLevelName": null,
                        "hasBusinessLicence": null,
                        "hasFoodCirculationPermit": null,
                        "flagOwnShop": "0",
                        "flagRecommend": null,
                        "sellerId": null,
                        "sellerName": "13026368741",
                        "state": 1,
                        "freezeTime": null,
                        "freezeEndTime": null,
                        "freezeDuration": null,
                        "freezeDurationUnit": null,
                        "freezeReason": "",
                        "areaNo": "110101",
                        "storeAddress": "111",
                        "storeAvatarUrl": "http://swy-mall-project.oss-cn-zhangjiakou.aliyuncs.com/PC/-1/2021-12/14/202112348170144251222.png",
                        "storeCoverUrl": "",
                        "storeCollect": null,
                        "storeEndTime": "2021-12-15 00:00:00",
                        "storeLogoUrl": "http://swy-mall-project.oss-cn-zhangjiakou.aliyuncs.com/PC/-1/2021-12/14/202112348170141698113.png",
                        "storeName": "aaa",
                        "storePhone": "",
                        "storeSales": null,
                        "storeZy": null,
                        "minPrice": null,
                        "longitude": "114.285891",
                        "latitude": "30.584761",
                        "sellerService": "",
                        "scopeBusiness": null,
                        "unifiedSocialCreditCode": null,
                        "freightTempMode": 3,
                        "freightRules": 1,
                        "isSupportReturnedCoupon": 0,
                        "groupBookingRules": null,
                        "isAutoFillCost": 0,
                        "costRatioValue": 0,
                        "createTime": "2021-12-21 00:00:00",
                        "uptTime": "2021-12-14 17:01:57",
                        "updateBy": 14,
                        "remarks": "encorehe",
                        "flagDel": "0",
                        "label": "aaa"
                    },
                    {
                        "storeId": 20,
                        "storeNo": "S000015",
                        "businessLicenceImageUrl": "",
                        "bankLicence": "",
                        "storeTypeId": 94,
                        "storeTypeName": "服装鞋包",
                        "companyName": null,
                        "companyAreaNo": null,
                        "companyAddress": null,
                        "companyPhone": null,
                        "foodCirculationPermitImageUrl": "",
                        "storeLevelId": null,
                        "storeLevelName": null,
                        "hasBusinessLicence": null,
                        "hasFoodCirculationPermit": null,
                        "flagOwnShop": "0",
                        "flagRecommend": null,
                        "sellerId": null,
                        "sellerName": "13026368743",
                        "state": 1,
                        "freezeTime": null,
                        "freezeEndTime": null,
                        "freezeDuration": null,
                        "freezeDurationUnit": null,
                        "freezeReason": "",
                        "areaNo": "110101",
                        "storeAddress": "111",
                        "storeAvatarUrl": "http://swy-mall-project.oss-cn-zhangjiakou.aliyuncs.com/PC/-1/2021-12/14/202112348174424676974.png",
                        "storeCoverUrl": "",
                        "storeCollect": null,
                        "storeEndTime": "2021-12-15 00:00:00",
                        "storeLogoUrl": "http://swy-mall-project.oss-cn-zhangjiakou.aliyuncs.com/PC/-1/2021-12/14/202112348174422956503.png",
                        "storeName": "aaa",
                        "storePhone": "",
                        "storeSales": null,
                        "storeZy": null,
                        "minPrice": null,
                        "longitude": "114.28868",
                        "latitude": "30.586313",
                        "sellerService": "",
                        "scopeBusiness": null,
                        "unifiedSocialCreditCode": null,
                        "freightTempMode": 3,
                        "freightRules": 1,
                        "isSupportReturnedCoupon": 0,
                        "groupBookingRules": null,
                        "isAutoFillCost": 0,
                        "costRatioValue": 0,
                        "createTime": "2021-12-14 00:00:00",
                        "uptTime": "2021-12-14 17:44:31",
                        "updateBy": 14,
                        "remarks": "encorehe",
                        "flagDel": "0",
                        "label": "aaa"
                    },
                    {
                        "storeId": 21,
                        "storeNo": "S000016",
                        "businessLicenceImageUrl": "",
                        "bankLicence": "",
                        "storeTypeId": 96,
                        "storeTypeName": "手机数码",
                        "companyName": null,
                        "companyAreaNo": null,
                        "companyAddress": null,
                        "companyPhone": null,
                        "foodCirculationPermitImageUrl": "",
                        "storeLevelId": 1,
                        "storeLevelName": "一星级",
                        "hasBusinessLicence": null,
                        "hasFoodCirculationPermit": null,
                        "flagOwnShop": "0",
                        "flagRecommend": "1",
                        "sellerId": 79,
                        "sellerName": "13512533343",
                        "state": 1,
                        "freezeTime": null,
                        "freezeEndTime": null,
                        "freezeDuration": null,
                        "freezeDurationUnit": null,
                        "freezeReason": "",
                        "areaNo": "420103",
                        "storeAddress": "泛海SOHO城7栋2105",
                        "storeAvatarUrl": "http://swy-mall-project.oss-cn-zhangjiakou.aliyuncs.com/PC/-1/2021-12/23/202112357160300313353.png",
                        "storeCoverUrl": "",
                        "storeCollect": null,
                        "storeEndTime": "2999-12-30 00:00:00",
                        "storeLogoUrl": "http://swy-mall-project.oss-cn-zhangjiakou.aliyuncs.com/PC/-1/2021-12/23/202112357160258295203.jpg",
                        "storeName": "加盟商1号店",
                        "storePhone": "",
                        "storeSales": null,
                        "storeZy": null,
                        "minPrice": null,
                        "longitude": "114.276347",
                        "latitude": "30.564093",
                        "sellerService": "",
                        "scopeBusiness": null,
                        "unifiedSocialCreditCode": null,
                        "freightTempMode": 3,
                        "freightRules": 1,
                        "isSupportReturnedCoupon": 0,
                        "groupBookingRules": "",
                        "isAutoFillCost": 0,
                        "costRatioValue": 0,
                        "createTime": "2021-12-23 00:00:00",
                        "uptTime": "2021-12-23 16:03:12",
                        "updateBy": 20,
                        "remarks": "wangkun",
                        "flagDel": "0",
                        "label": "加盟商1号店"
                    }
                ],
                cityList: [
                    {
                        value: '111',
                        label: 'New York'
                    },
                    {
                        value: '222',
                        label: 'London'
                    },
                    {
                        value: '33',
                        label: 'Sydney'
                    },
                    {
                        value: 'Ottawa',
                        label: 'Ottawa'
                    },
                    {
                        value: 'Paris',
                        label: 'Paris'
                    },
                    {
                        value: 'Canberra',
                        label: 'Canberra'
                    }
                ],
                model1: 1,
                model10: [],
                model12: [],
                model13: '',
                model31: '',
                model32: '',
                model33: '',
                model34: [],
                model35: [],
                model36: []
            }
        },
        methods: {
            beforeChange(val){
                this.$Modal.confirm({
                    title: '提示',
                    content: '是否确认本条支付凭证审核通过？通过后将不可更改！',
                    onOk: () => {
                        this.visibleSelcted = false;
                        // this.$refs.ele.hidePop()
                    },
                    onCancel:()=>{
                        this.visibleSelcted = true;
                        // this.$refs.ele.showPop()
                    }
                });
            },
            more (num) {
                return 'more' + num;
            },
            handleCreate (val) {
                console.log(111,val);
                this.cityList.push({
                    value: val,
                    label: val
                });
            }
        }
    }
</script>
